/*
 * DIO_private.h
 *
 *  Created on: Aug 12, 2020
 *      Author: mazen
 */

#ifndef INCLUDE_DIO_PRIVATE_H_
#define INCLUDE_DIO_PRIVATE_H_

/* DIO register definitions */

#define DIO_POTRA_BASE_ADDR 0x40010800
#define DIO_POTRB_BASE_ADDR 0x40010C00
#define DIO_POTRC_BASE_ADDR 0x40011000

#define DIO_REG32_DEF(base,offset) *((volatile u32*)((base) + (offset)))


/* PORTA REGISTERS */
#define GPIOA_CRL	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x00)
#define GPIOA_CRH	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x04)
#define GPIOA_IDR	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x08)
#define GPIOA_ODR	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x0c)
#define GPIOA_BSRR	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x10)
#define GPIOA_BRR	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x14)
#define GPIOA_LCKR	DIO_REG32_DEF(DIO_POTRA_BASE_ADDR,0x18)

/* PORTB REGISTERS */

#define GPIOB_CRL	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x00)
#define GPIOB_CRH	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x04)
#define GPIOB_IDR	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x08)
#define GPIOB_ODR	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x0c)
#define GPIOB_BSRR	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x10)
#define GPIOB_BRR	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x14)
#define GPIOB_LCKR	DIO_REG32_DEF(DIO_POTRB_BASE_ADDR,0x18)

/* PORTC REGISTERS */

#define GPIOC_CRL	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x00)
#define GPIOC_CRH	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x04)
#define GPIOC_IDR	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x08)
#define GPIOC_ODR	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x0c)
#define GPIOC_BSRR	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x10)
#define GPIOC_BRR	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x14)
#define GPIOC_LCKR	DIO_REG32_DEF(DIO_POTRC_BASE_ADDR,0x18)



#endif /* INCLUDE_DIO_PRIVATE_H_ */
